export const columns = [
	{
		field: 'field1',
		headerText: 'header1',
		visible: true,
		order: 0,
	},
	{
		field: 'field2',
		headerText: 'header2',
		order: undefined,
		visible: true,
	},
	{
		field: 'field3',
		headerText: 'header3',
		visible: true,
		order: 2,
	},
	{
		field: 'field4',
		headerText: 'header4',
		visible: false,
	},
	{
		field: 'field5',
		headerText: 'header5',
		visible: false,
		order: 3,
	},
	{
		field: 'field6',
		headerText: 'header6',
		visible: true,
		order: 4,
	},
	{
		field: 'field7',
		headerText: 'header7',
		visible: true,
		order: 5,
	},
	{
		field: 'field8',
		headerText: 'header8',
		visible: true,
		order: 6,
	},
	{
		field: 'field9',
		headerText: 'header9',
		visible: true,
		order: undefined,
	},
	{
		field: 'field10',
		headerText: 'header10',
		visible: true,
		order: undefined,
	},
	{
		field: 'field11',
		headerText: 'header11',
		visible: true,
		order: undefined,
	},
	{
		field: 'field12',
		headerText: 'header12',
		visible: true,
		order: undefined,
	},
	{
		field: 'field13',
		headerText: 'header13',
		visible: true,
		order: undefined,
	},
	{
		field: 'field14',
		headerText: 'header14',
		visible: true,
		order: undefined,
	},
	{
		field: 'field15',
		headerText: 'header15',
		visible: true,
		order: undefined,
	},
	{
		field: 'field16',
		headerText: 'header16',
		visible: true,
		order: undefined,
	},
];
